/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  safelist: [
    'hover:text-theme-red',
    'hover:border-theme-red',
    'hover:text-theme-blue',
    'hover:border-theme-blue',
    'hover:text-theme-green',
    'hover:border-theme-green',
    'hover:text-theme-yellow',
    'hover:border-theme-yellow',
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "var(--on-secondary-container)",
        "surface-variant": "#e9e1de",
        "on-primary-fixed": "var(--on-primary-fixed)",
        "tertiary": "#5e6000",
        "on-background": "var(--on-background)",
        "on-tertiary-fixed": "#1c1d00",
        "on-primary": "var(--on-primary)",
        "inverse-primary": "#92d1d4",
        "outline-variant": "#bfc8c8",
        "surface-bright": "#fff8f5",
        "secondary-fixed": "#ffdad5",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
        "surface-container-highest": "var(--surface-container-highest)",
        "primary-fixed-dim": "#92d1d4",
        "outline": "#6f7979",
        "tertiary-container": "#777900",
        "on-primary-container": "#f3ffff",
        "tertiary-fixed": "#e7ea54",
        "background": "var(--background)",
        "inverse-on-surface": "#f7efec",
        "inverse-surface": "#33302e",
        "surface-dim": "var(--surface-dim)",
        "primary-container": "var(--primary-container)",
        "on-surface-variant": "var(--on-surface-variant)",
        "surface-tint": "var(--surface-tint)",
        "primary-fixed": "#adeef1",
        "on-error": "#ffffff",
        "primary": "var(--primary)",
        "surface-container-low": "var(--surface-container-low)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "secondary-fixed-dim": "#ffb4a9",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "on-tertiary-fixed-variant": "#484a00",
        "surface": "var(--surface)",
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        "surface-container": "var(--surface-container)",
        "secondary-container": "#d9362b",
        "secondary": "var(--secondary)",
        "on-tertiary-container": "#fffbff",
        "on-surface": "var(--on-surface)",
        "tertiary-fixed-dim": "#cacd39",
        "on-secondary": "var(--on-secondary)",
        "on-error-container": "#93000a",
        "surface-container-high": "var(--surface-container-high)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
        
        "theme-blue": "var(--theme-blue)",
        "theme-red": "var(--theme-red)",
        "theme-green": "var(--theme-green)",
        "theme-yellow": "var(--theme-yellow)",
        "theme-grey": "var(--theme-grey)"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin": "32px",
        "shadow-offset": "6px",
        "border-width": "3px",
        "unit": "8px",
        "gutter": "24px",
        "container-max": "1280px",
        "border-width-heavy": "6px",
        "border-width-std": "4px"
      },
      fontFamily: {
        "body-md": ["Hanken Grotesk"],
        "label-md": ["JetBrains Mono"],
        "headline-md": ["Space Grotesk"],
        "body-lg": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Space Grotesk"],
        "button": ["Space Grotesk"],
        "headline-lg": ["Space Grotesk"],
        "display-2xl": ["Space Grotesk"],
        "label-bold": ["JetBrains Mono"]
      },
      fontSize: {
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "headline-md": ["24px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-lg-mobile": ["32px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "button": ["16px", { "lineHeight": "1", "fontWeight": "700" }],
        "headline-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "display-2xl": ["120px", { "lineHeight": "110px", "letterSpacing": "-0.04em", "fontWeight": "800" }],
        "label-bold": ["14px", { "lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}